// AUTO-GENERATED - DO NOT EDIT
// Generated by dsl/src/codegen.ts
//
// Global type declarations for plan authoring.
// Key, P, and coalesce are injected as globals by the dslc compiler.
// This file provides TypeScript type information for editor support.

import type { Key as KeyType } from "@ranking-dsl/generated";
import type { P as PType } from "@ranking-dsl/generated";
import type { coalesce as coalesceType } from "@ranking-dsl/runtime";

declare global {
  /**
   * Key registry - column references for vm/filter expressions.
   * Injected by dslc compiler.
   */
  const Key: typeof KeyType;

  /**
   * Param registry - runtime parameter references.
   * Injected by dslc compiler.
   */
  const P: typeof PType;

  /**
   * Coalesce function for null handling in natural expressions.
   * Usage: Key.score * coalesce(P.weight, 0.2)
   * Injected by dslc compiler.
   */
  const coalesce: typeof coalesceType;
}

export {};
