// AUTO-GENERATED - DO NOT EDIT
// Generated by dsl/src/codegen.ts
//
// Global type declarations for plan authoring.
// Key, P, EP, coalesce, and regex are injected as globals by the dslc compiler.
// This file provides TypeScript type information for editor support.

import type { Key as KeyType } from "@ranking-dsl/generated";
import type { P as PType } from "@ranking-dsl/generated";
import type { EP as EPType } from "@ranking-dsl/generated";
import type { coalesce as coalesceType, regex as regexType } from "@ranking-dsl/runtime";

declare global {
  /**
   * Key registry - column references for vm/filter expressions.
   * Injected by dslc compiler.
   */
  const Key: typeof KeyType;

  /**
   * Param registry - runtime parameter references.
   * Injected by dslc compiler.
   */
  const P: typeof PType;

  /**
   * Endpoint registry - endpoint references for source tasks.
   * Usage: ctx.follow({ endpoint: EP.redis.default, fanout: 10 })
   * Injected by dslc compiler.
   */
  const EP: typeof EPType;

  /**
   * Coalesce function for null handling in natural expressions.
   * Usage: Key.score * coalesce(P.weight, 0.2)
   * Injected by dslc compiler.
   */
  const coalesce: typeof coalesceType;

  /**
   * Regex function for pattern matching in natural predicates.
   * Usage: regex(Key.title, "^test") or regex(Key.title, P.pattern, "i")
   * Injected by dslc compiler.
   */
  const regex: typeof regexType;
}

export {};
