// AUTO-GENERATED - DO NOT EDIT
// Generated by dsl/src/codegen.ts from registry/capabilities.toml
#pragma once

#include <array>
#include <optional>
#include <string_view>

namespace rankd {

enum class CapabilityStatus { Implemented, Draft, Deprecated, Blocked };

// Simple schema representation (subset of JSON Schema)
// For now, we only need to track:
// - has_schema: false = no payload allowed
// - additional_properties: false = only allowed keys accepted
struct PayloadSchema {
  bool has_schema;            // false = no payload allowed
  bool additional_properties; // true = allow extra keys
  // Property definitions can be added as needed
};

struct CapabilityMeta {
  std::string_view id;
  std::string_view rfc;
  std::string_view name;
  CapabilityStatus status;
  std::string_view doc;
  PayloadSchema schema;
};

inline constexpr size_t kCapabilityCount = 1;
inline constexpr std::string_view kCapabilityRegistryDigest =
    "470c3bc1e074d48d7a4e7f7807f44201bfddd4c97e09e575c796f197567dacfa";

inline constexpr std::array<CapabilityMeta, kCapabilityCount>
    kCapabilityRegistry = {{
        {"cap.rfc.0001.extensions_capabilities.v1",
         "0001",
         "extensions_capabilities",
         CapabilityStatus::Implemented,
         "Base extensions/capabilities mechanism for IR evolution",
         {.has_schema = true, .additional_properties = false}},
    }};

} // namespace rankd
