// AUTO-GENERATED - DO NOT EDIT
// Generated by dsl/src/codegen.ts from registry/capabilities.toml
#pragma once

#include <array>
#include <optional>
#include <string_view>

namespace rankd {

enum class CapabilityStatus { Implemented, Draft, Deprecated, Blocked };
enum class PropertyType { Boolean, String, Number, Array, Object, Unknown };

// Property metadata for type checking
struct PropertyMeta {
  std::string_view name;
  PropertyType type;
};

// Simple schema representation (subset of JSON Schema)
struct PayloadSchema {
  bool has_schema;            // false = no payload allowed
  bool additional_properties; // true = allow extra keys
  const std::string_view
      *allowed_keys;       // pointer to array of allowed property names
  size_t num_allowed_keys; // number of allowed properties
  const std::string_view
      *required_keys;       // pointer to array of required property names
  size_t num_required_keys; // number of required properties
  const PropertyMeta *property_types; // pointer to array of property type info
  size_t num_property_types;          // number of property type entries
};

struct CapabilityMeta {
  std::string_view id;
  std::string_view rfc;
  std::string_view name;
  CapabilityStatus status;
  std::string_view doc;
  PayloadSchema schema;
};

inline constexpr size_t kCapabilityCount = 2;
inline constexpr std::string_view kCapabilityRegistryDigest =
    "3537d0e4f5fe759dd852f53a81972534f50d14cb6e6a7772b5bf12cadb81d4c8";

inline constexpr std::array<CapabilityMeta, kCapabilityCount>
    kCapabilityRegistry = {{
        {"cap.rfc.0001.extensions_capabilities.v1",
         "0001",
         "extensions_capabilities",
         CapabilityStatus::Implemented,
         "Base extensions/capabilities mechanism for IR evolution",
         {.has_schema = true,
          .additional_properties = false,
          .allowed_keys = nullptr,
          .num_allowed_keys = 0,
          .required_keys = nullptr,
          .num_required_keys = 0,
          .property_types = nullptr,
          .num_property_types = 0}},
        {"cap.rfc.0005.key_effects_writes_exact.v1",
         "0005",
         "key_effects_writes_exact",
         CapabilityStatus::Draft,
         "Strict shape enforcement for branching meta-tasks (RFC0005)",
         {.has_schema = true,
          .additional_properties = false,
          .allowed_keys = nullptr,
          .num_allowed_keys = 0,
          .required_keys = nullptr,
          .num_required_keys = 0,
          .property_types = nullptr,
          .num_property_types = 0}},
    }};

} // namespace rankd
