// AUTO-GENERATED - DO NOT EDIT
// Generated by dsl/src/codegen.ts
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

#include "key_registry.h" // for Status

namespace rankd {

enum class FeatureId : uint32_t {
  esr_country = 20001,
  esr_media_age_hours = 20002,
};

enum class FeatureType { Int, Float, String, Bool };

struct FeatureMeta {
  uint32_t id;
  std::string_view stage;
  std::string_view name;
  FeatureType type;
  bool nullable;
  Status status;
};

inline constexpr size_t kFeatureCount = 2;
inline constexpr std::string_view kFeatureRegistryDigest =
    "fd17942286e9ac42d9045869832c82cec7bb1b830ec488d65ae3ae924aba94ba";

inline constexpr std::array<FeatureMeta, kFeatureCount> kFeatureRegistry = {{
    {20001, "esr", "country", FeatureType::String, true, Status::Active},
    {20002, "esr", "media_age_hours", FeatureType::Float, true, Status::Active},
}};

} // namespace rankd
