// AUTO-GENERATED - DO NOT EDIT
// Generated by dsl/src/codegen.ts
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace rankd {

enum class KeyId : uint32_t {
  id = 1,
  model_score_1 = 1001,
  model_score_2 = 1002,
  final_score = 2001,
  country = 3001,
  title = 3002,
  features_esr = 4001,
  features_lsr = 4002,
};

// Helper to convert KeyId to uint32_t (avoids verbose static_cast)
constexpr uint32_t key_id(KeyId k) noexcept { return static_cast<uint32_t>(k); }

enum class KeyType { Int, Float, String, Bool, FeatureBundle };
enum class Status { Active, Deprecated, Blocked };

struct KeyMeta {
  uint32_t id;
  std::string_view name;
  KeyType type;
  bool nullable;
  Status status;
  bool allow_read;
  bool allow_write;
  uint32_t replaced_by; // 0 if none
  bool has_default;
  std::string_view default_json;
};

inline constexpr size_t kKeyCount = 8;
inline constexpr std::string_view kKeyRegistryDigest =
    "80e926e8520e814505a2150c66e9069615c0b500e8ea17b1d4a63b83df650852";

inline constexpr std::array<KeyMeta, kKeyCount> kKeyRegistry = {{
    {1, "id", KeyType::Int, false, Status::Active, true, false, 0, false, ""},
    {1001, "model_score_1", KeyType::Float, false, Status::Active, true, true,
     0, true, "0"},
    {1002, "model_score_2", KeyType::Float, false, Status::Active, true, true,
     0, true, "0"},
    {2001, "final_score", KeyType::Float, false, Status::Active, true, true, 0,
     true, "0"},
    {3001, "country", KeyType::String, true, Status::Active, true, true, 0,
     false, ""},
    {3002, "title", KeyType::String, true, Status::Active, true, true, 0, false,
     ""},
    {4001, "features_esr", KeyType::FeatureBundle, true, Status::Active, true,
     true, 0, false, ""},
    {4002, "features_lsr", KeyType::FeatureBundle, true, Status::Active, true,
     true, 0, false, ""},
}};

} // namespace rankd
