// AUTO-GENERATED - DO NOT EDIT
// Generated by dsl/src/codegen.ts
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

#include "keys.h" // for Status

namespace rankd {

enum class ParamId : uint32_t {
  media_age_penalty_weight = 1,
  blocklist_regex = 2,
  esr_cutoff = 3,
};

enum class ParamType { Int, Float, String, Bool };

struct ParamMeta {
  uint32_t id;
  std::string_view name;
  ParamType type;
  bool nullable;
  Status status;
  bool allow_read;
  bool allow_write;
  uint32_t replaced_by; // 0 if none
};

inline constexpr size_t kParamCount = 3;
inline constexpr std::string_view kParamRegistryDigest =
    "02c816622d8b6f51eedb60d07d394984df1ac597ce81b76f1ad06ff2a3b0eb43";

inline constexpr std::array<ParamMeta, kParamCount> kParamRegistry = {{
    {1, "media_age_penalty_weight", ParamType::Float, false, Status::Active,
     true, true, 0},
    {2, "blocklist_regex", ParamType::String, true, Status::Active, true, true,
     0},
    {3, "esr_cutoff", ParamType::Float, false, Status::Active, true, true, 0},
}};

} // namespace rankd
