// AUTO-GENERATED - DO NOT EDIT
// Generated by dsl/src/codegen.ts from registry/validation.toml
#pragma once

#include <array>
#include <cstdint>
#include <regex>
#include <string>
#include <string_view>

namespace rankd {
namespace validation {

// ============================================================
// Patterns
// ============================================================

inline const std::string kPlanNamePattern = "^[A-Za-z0-9_]+$";
inline const std::string kNodeIdPattern = "^[A-Za-z0-9_]+$";

// ============================================================
// Validation functions
// ============================================================

inline bool is_valid_plan_name(const std::string &value) {
  static const std::regex pattern(kPlanNamePattern);
  return std::regex_match(value, pattern);
}

inline bool is_valid_node_id(const std::string &value) {
  static const std::regex pattern(kNodeIdPattern);
  return std::regex_match(value, pattern);
}

// ============================================================
// Limits
// ============================================================

inline constexpr uint32_t kMaxFanout = 10000000;
inline constexpr uint32_t kPlanSchemaVersion = 1;

// ============================================================
// Enums
// ============================================================

inline constexpr std::array<std::string_view, 2> kRegexFlags = {{
    "",
    "i",
}};

inline constexpr std::array<std::string_view, 6> kCmpOperators = {{
    "==",
    "!=",
    "<",
    "<=",
    ">",
    ">=",
}};

inline constexpr std::string_view kValidationDigest =
    "54377dc5d599fdbbb14189ef616b28c0f77114997ecd07bde65a5899254d4a57";

} // namespace validation
} // namespace rankd
